# Tasks for Java 21 installation
---
- name: Check if Java is installed
  command: java -version
  register: java_version
  failed_when: false
  changed_when: false

- name: Download OpenJDK deb package
  get_url:
    url: "{{ java_package_url }}"
    dest: "{{ jdk_deb_file }}"
  when: java_version.rc != 0

- name: Install OpenJDK from deb file
  apt:
    deb: "{{ jdk_deb_file }}"
    state: present
    update_cache: yes
  when: java_version.rc != 0

- name: Verify Java installation
  command: java -version
  register: java_ver
  when: java_version.rc != 0
  failed_when: java_ver.rc != 0